###############################
# BASE stage                  #
# Minimal to install samtools #
###############################

FROM ubuntu:22.04 AS base

# Install dependencies for samtools
# For the installer script:
# - curl: download files
# For samtools and htslib:
# - build-essential: for compiling source code (gcc, g++, make)
# - autoconf, automake: for compiling source code
# - zlib1g-dev, libbz2-dev, liblzma-dev: compression libraries for samtools
# - libcurl4-openssl-dev: for curl dev features in samtools
RUN apt-get update && apt-get install -y \
    build-essential \
    autoconf \
    automake \
    curl \
    zlib1g-dev \
    libbz2-dev \
    liblzma-dev \
    libncurses5-dev \
    libcurl4-openssl-dev \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /opt
WORKDIR /opt/repo

# Build time argument for SAMTOOLS version - argument name can be anything
ARG SAMTOOLS_VERSION="1.14" 
ARG SAMTOOLS_SCRIPT_URL="https://github.com/team113sanger/samtools-install-script/releases/download/1.0.0/install_samtools.sh"

# Actual installation of samtools (defaults to installing to /usr/local)
RUN curl -sSL $SAMTOOLS_SCRIPT_URL | bash -s -- $SAMTOOLS_VERSION

##############################
# TEST stage only            #
# Test samtools installation #
##############################
FROM base AS test

# Create a non-root user
ENV USER_NAME=testuser
RUN useradd -m ${USER_NAME:?} 

# Create test directory
WORKDIR /opt/test

# Copy test files
COPY --chown=testuser:testuser ./tests/* /opt/test/

# Make sure the test script is executable
RUN chmod +x *.sh && chown "${USER_NAME:?}:${USER_NAME:?}" -R .

# Switch to the non-root user
USER testuser

CMD ["bash"]